routes/web.php
<?php
use App\Http\Controllers\AlumnoController;
use App\Http\Controllers\MaestroController;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return view('auth/login');
});

Route::resource('alumnos', AlumnoController::class);
Route::resource('maestros', MaestroController::class);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Maestro.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Maestro
 *
 * @property $id
 * @property $nombre
 * @property $grado
 * @property $seccion
 * @property $created_at
 * @property $updated_at
 *
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Maestro extends Model
{
    
    static $rules = [
		'nombre' => 'required',
		'grado' => 'required',
		'seccion' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['nombre','grado','seccion'];



}

app/Models/maestros.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class maestros extends Model
{
    use HasFactory;
}

app/Http/Controllers/MaestroController.php
<?php

namespace App\Http\Controllers;

use App\Models\Maestro;
use Illuminate\Http\Request;

/**
 * Class MaestroController
 * @package App\Http\Controllers
 */
class MaestroController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $maestros = Maestro::paginate();

        return view('maestro.index', compact('maestros'))
            ->with('i', (request()->input('page', 1) - 1) * $maestros->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $maestro = new Maestro();
        return view('maestro.create', compact('maestro'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Maestro::$rules);

        $maestro = Maestro::create($request->all());

        return redirect()->route('maestros.index')
            ->with('success', 'Maestro created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $maestro = Maestro::find($id);

        return view('maestro.show', compact('maestro'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $maestro = Maestro::find($id);

        return view('maestro.edit', compact('maestro'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Maestro $maestro
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Maestro $maestro)
    {
        request()->validate(Maestro::$rules);

        $maestro->update($request->all());

        return redirect()->route('maestros.index')
            ->with('success', 'Maestro updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $maestro = Maestro::find($id)->delete();

        return redirect()->route('maestros.index')
            ->with('success', 'Maestro deleted successfully');
    }
}

resources/views/maestro/create.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('Create') }} Maestro
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">{{ __('Create') }} Maestro</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('maestros.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('maestro.form')

                        </form>
                         <br><a class="btn btn-danger" href="/alumnos" role="button">Back</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/maestro/edit.blade.php
@extends('layouts.app')

@section('template_title')
    {{ __('Update') }} Maestro
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">{{ __('Update') }} Maestro</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('maestros.update', $maestro->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('maestro.form')
                        </form>
                    <br><a class="btn btn-danger" href="/maestros" role="button">Back</a>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/maestro/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('nombre') }}
            {{ Form::text('nombre', $maestro->nombre, ['class' => 'form-control' . ($errors->has('nombre') ? ' is-invalid' : ''), 'placeholder' => 'Nombre']) }}
            {!! $errors->first('nombre', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('grado') }}
            {{ Form::text('grado', $maestro->grado, ['class' => 'form-control' . ($errors->has('grado') ? ' is-invalid' : ''), 'placeholder' => 'Grado']) }}
            {!! $errors->first('grado', '<div class="invalid-feedback">:message</div>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('seccion') }}
            {{ Form::text('seccion', $maestro->seccion, ['class' => 'form-control' . ($errors->has('seccion') ? ' is-invalid' : ''), 'placeholder' => 'Seccion']) }}
            {!! $errors->first('seccion', '<div class="invalid-feedback">:message</div>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">{{ __('Submit') }}</button>
    </div>
</div>

resources/views/maestro/index.blade.php
@extends('layouts.app')

@section('template_title')
    Maestro
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Maestro') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('maestros.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Create New') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>

										<th>Nombre</th>
										<th>Grado</th>
										<th>Seccion</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($maestros as $maestro)
                                        <tr>
                                            <td>{{ ++$i }}</td>

											<td>{{ $maestro->nombre }}</td>
											<td>{{ $maestro->grado }}</td>
											<td>{{ $maestro->seccion }}</td>

                                            <td>
                                                <form action="{{ route('maestros.destroy',$maestro->id) }}" method="POST">
                                                    <a class="btn btn-sm btn-primary " href="{{ route('maestros.show',$maestro->id) }}"><i class="fa fa-fw fa-eye"></i> {{ __('Show') }}</a>
                                                    <a class="btn btn-sm btn-success" href="{{ route('maestros.edit',$maestro->id) }}"><i class="fa fa-fw fa-edit"></i> {{ __('Edit') }}</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> {{ __('Delete') }}</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            <br><a class="btn btn-danger" href="home" role="button">Dashboard</a>
                        </div>
                    </div>
                </div>
                {!! $maestros->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/maestro/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $maestro->name ?? "{{ __('Show') Maestro" }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">{{ __('Show') }} Maestro</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('maestros.index') }}"> {{ __('Back') }}</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Nombre:</strong>
                            {{ $maestro->nombre }}
                        </div>
                        <div class="form-group">
                            <strong>Grado:</strong>
                            {{ $maestro->grado }}
                        </div>
                        <div class="form-group">
                            <strong>Seccion:</strong>
                            {{ $maestro->seccion }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection